### PR TITLE
Add "Smart" component recommender to ElectricCircuits Editor. Closes #103

### LINKED ISSUE #103: Smart Recommender Part Browser
It might be nice to integrate a "smart" recommender for components that uses the models trained by @brollb to work with `ElectricCircuitsEditor` Visualizer.  Specific details are not very clear at this point but based on the conversation we had, It should be a browsable list of next few components.

### PR DESCRIPTION
**Pull request by umesh-timalsina**

### CODE REVIEW

**Comment by brollb** [comment]
Nice. Can you post a screenshot?

**Comment by umesh-timalsina** [comment]
@brollb I have a mp4 here. LMK if that works (Pardon the unnecessary frames).

https://user-images.githubusercontent.com/11476842/111396076-54222780-868c-11eb-8822-a9260e003d32.mp4

**Comment by umesh-timalsina** [comment]
@brollb. What do you think of the video so far? We can use some animation/scaling we discussed before to make it more fancy. Are there any redflags you see with a button based approach? I can see displaying a form for selection of available example models to use might make it more usable.

**Comment by brollb** [comment]
I think the video looks good for a first pass. There are a couple minor aesthetic things like the vertical spacing (the components seem closer to the top then the bottom) and the red background on the X is a little weird (I would probably just remove it and have the box close on unfocus/clicking outside of it).

As far as the model selection, it would be nice to make it configurable but I would try to avoid setting it each time the box opens. I would either opt for a config icon where you can set the model to use next to the button or an indicator next to the button where you can select the model to use. Maybe the config icon and then displaying it at the bottom of the opened component recommender would be the way to go.

**Comment by umesh-timalsina** [comment]
@brollb. Here's an implementation I came up with for configuration. Its semi hardcoded but works.

image

**Comment by brollb** [comment]
What if you made it the cog wheel icon that, when clicked, drops down a small form with the one entry (model/algorithm) for now? 

Also, there is probably a better name for the recommended components. What if you call it "Component Toolbox" or something and then add a divider (like `<hr>`) and display all the components below it? The window will need to be scrollable but then we would be able to forgo the part browser all together.

**Comment by umesh-timalsina** [comment]
Rather than adding a separate graph as shown in this PR. #118 adds a component Browser. 
image. 

As suggested here, I think a betterway would be to sort components in the smart component browser which works better for demo purposes.

**Comment by umesh-timalsina** [comment]
This now looks like the following:
image
image

**Comment by umesh-timalsina** [comment]
It might be nice to figure out what the failures would look like. Currently a simple alert ? Might be related to #82. The error messages are not informative enough to display in a custom HTML container.

**Pull request merged**
