### PR TITLE
Display component links based on recommendation Plugin results. Closes #126

### LINKED ISSUE #126: "Smart" Link Prediction in ElectricCircuitsEditor
@brollb is working a plugin that adds link prediction. While, in the demo today, a hard coded version of link prediction was working based on progress made in #103, I have reverted the changes and I think #114 should be merged first and should be extended for the link prediction in `ElectricCircuits` once the general format for recommendation plugin is formalized.

### PR DESCRIPTION
**Pull request by umesh-timalsina**

### CODE REVIEW

**Comment by umesh-timalsina** [comment]
Now that the recommended components are added to the circuit graph based on variable opacity, I think a workflow for this addition should be like:
1. Pass on a temporary node creation event to `webGME`, let the visualizer control create nodes and assign wires.
2. If no recommendation is taken by the user, remove the created  nodes/wires.
3. If one of the recommendation is selected, remove the other two and let `webGME` handle the removal of nodes.

**Comment by brollb** [comment]
This will be nice to merge as it will make testing recommendation models (like https://github.com/symbench/electric-circuits/pull/120) easier. What is blocking it currently? Would it be possible to move the remaining tasks to a separate issue/PR?

**Comment by umesh-timalsina** [comment]
Sure. I will finish this up today. :)

**Comment by umesh-timalsina** [comment]
Currently getting `SPICE` nodes from the plugin instead of  `GME` Pin ids:
```
"[
  [
    [
      {
        "type": "Voltage",
        "pins": [
          "N0007",
          "N0006"
        ]
      }
    ],
    0.5
  ],
  [
    [
      {
        "type": "Resistor",
        "pins": [
          "N0007",
          "N0006"
        ]
      }
    ],
    0.5
  ]
]"
```

**Pull request merged**
